Master 1.0 (#54)
* Add history and report feature (#51)

* Add history and report feature

* password (#50)

* Bugs fixed

* item_service.xml redesing

* errores

* errores

* Conflicts resolved

---------

Co-authored-by: Karla <kramirez32@ucol.mx>

* Edit feature as Product Owner request

* Fix bug

A method was deleted on another, re-add it.

* spa_text image added to item_appointments_accepted.xml

---------

Co-authored-by: Jose Avalos <79113549+joseavaalos@users.noreply.github.com>
Co-authored-by: Karla <kramirez32@ucol.mx>

* Bug fix status user (#52)

* EditProfileFragment.kt modified to fix the bug that when you edit your profile as a client, it logs you out of the session

* login button design

* login button design 1.2

* login button design 1.3

* merge 2.0 (lo que se perdió con el pull request "password")

* Merge incompleto
Error: imágenes de users

---------

Co-authored-by: Zama15 <112733483+Zama15@users.noreply.github.com>
Co-authored-by: Jose Avalos <79113549+joseavaalos@users.noreply.github.com>